/* Generated by Together */

package com.pb.despair.model;

public interface DevelopmentTypeInterface {
    double getConstructionCost();

    public String getName();
    public int getID();
    /**
     * Method getGridCode.
     * @return String
     */
    char getGridCode();

    /**
     * Method setConstructionCost.
     * @param d
     */
    void setConstructionCost(double d);

    /**
     * @param d
     */
    void setMaintenanceCost(double d);
    
    void setAddASC(double d);
    
    void setNewASC(double d);
    
    void setRentDiscount(double d);
    
    double getRentDiscountFactor(int age);

}
