/* Generated by Together */

package com.pb.despair.model;

public class OverflowException extends Exception {
public OverflowException() {
        super();
    }

public OverflowException(String par1) {
        super(par1);
    }
}
