/* Generated by Together */

package com.pb.despair.model;

/**
 * This class is used to track the days that are being simulated, e.g. 7 typical weekdays, or perhaps a typical weekday day and a typical weekend day. 
 */
public class SimulationDays {
}
