/* Generated by Together */

package com.pb.tlumip.ha;

import com.pb.models.pecas.AbstractTAZ;
import com.pb.models.pecas.Alternative;
import com.pb.models.pecas.LogitModel;

import java.util.Iterator;

public class HouseholdLocationLogit extends LogitModel {
    void addAlternatives(AbstractTAZ[] zones) {
        for (int z=0;z<zones.length;z++) {
            Household.HouseholdLocation h = new Household.HouseholdLocation((Household) null, zones[z]);
            addAlternative(h);
        }
    }



    public void addAlternative(Alternative a) {
        if (! (a instanceof Household.HouseholdLocation)) {
            throw new Error("Can only add Household.HouseholdLocation objects to this logit model");
        }
        super.addAlternative(a);
    }

    public void setHousehold(Household h) {
        Iterator it = alternatives.iterator();
        while (it.hasNext()) {
            Household.HouseholdLocation hl = (Household.HouseholdLocation) it.next();
            hl.setHousehold(h);
        }
    }
}

