/*
 * Copyright  2005 PB Consult Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/* Generated by Together */

package com.pb.tlumip.ha;

import com.pb.models.pecas.AbstractZone;
import com.pb.models.pecas.Alternative;
import com.pb.models.pecas.LogitModel;

import java.util.Iterator;

public class HouseholdLocationLogit extends LogitModel {
    void addAlternatives(AbstractZone[] zones) {
        for (int z=0;z<zones.length;z++) {
            Household.HouseholdLocation h = new Household.HouseholdLocation((Household) null, zones[z]);
            addAlternative(h);
        }
    }



    public void addAlternative(Alternative a) {
        if (! (a instanceof Household.HouseholdLocation)) {
            throw new Error("Can only add Household.HouseholdLocation objects to this logit model");
        }
        super.addAlternative(a);
    }

    public void setHousehold(Household h) {
        Iterator it = alternatives.iterator();
        while (it.hasNext()) {
            Household.HouseholdLocation hl = (Household.HouseholdLocation) it.next();
            hl.setHousehold(h);
        }
    }
}

