/*
 * Copyright  2005 PB Consult Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/* Generated by Together */

package com.pb.tlumip.ha;

import com.pb.models.pecas.ChoiceModelOverflowException;
import com.pb.models.pecas.*;

import java.util.Iterator;

public class HouseholdSpaceChoiceLogit extends LogitModel {

    HouseholdSpaceChoiceLogit(AllHouseholds ahh) {
        Iterator i = ahh.getAllowedIn().iterator();
        while (i.hasNext()) {
          DevelopmentTypeInterface dt = (DevelopmentTypeInterface) i.next();
          addAlternative(new SpaceChoiceAlternative(dt));
        }
    }
    Household h;
    AbstractZone z;

    class SpaceChoiceAlternative implements Alternative {
        DevelopmentTypeInterface dt;
        SpaceChoiceAlternative(DevelopmentTypeInterface dt) {
            this.dt = dt;
        }

        public double getUtility(double higherLevelDispersionParameter) {
            if (h==null) throw new Error("Forgot to set household in SpaceChoiceLogitModel");
            if (z==null) throw new Error("Forgot to set zone in SpaceChoiceLogitModel");
            return h.utilityOfSpaceAndPrice(z,dt, true, Household.dwellingChoiceDispersionParameter);
        }


    }
    DevelopmentTypeInterface monteCarloSpaceChoice() throws NoAlternativeAvailable, ChoiceModelOverflowException {
        return ((SpaceChoiceAlternative) super.monteCarloChoice()).dt;
    }

}

