/*
 * Copyright  2005 PB Consult Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/* Generated by Together */

package com.pb.tlumip.ha;
import com.pb.common.util.ResourceUtil;

import java.util.ResourceBundle;


public class WriteLogsumsToTextFiles {
    public static void main(String[] args) {
        ResourceBundle rb = ResourceUtil.getResourceBundle( "ha" );
        String path = ResourceUtil.getProperty(rb, "outputPopulation.path");
        HAModel.dm.exportTable("DC LOGSUMS", path+"Logsums");
        System.exit(0);
    }
}
