/* Generated by Together */

package com.pb.tlumip.ha;
import com.pb.common.util.ResourceUtil;

import java.util.ResourceBundle;


public class WritePopulationAndGridCellsToTextFiles {
    public static void main(String[] args) {
        ResourceBundle rb = ResourceUtil.getResourceBundle( "ha" );
        String path = ResourceUtil.getProperty(rb, "outputPopulation.path");
        HAModel.dm.exportTable("SynPopH", path+"SynPopH");
        HAModel.dm.exportTable("SynPopP", path+"SynPopP");
        path = ResourceUtil.getProperty(rb, "outputGridcells.path");
        HAModel.dm.exportTable("GridCells", path+"GridCells");
        System.exit(0);
    }
}
