/* Generated by Together */

package com.pb.tlumip.ha;
import com.pb.common.util.ResourceUtil;

import java.util.ResourceBundle;


public class WriteLogsumsToTextFiles {
    public static void main(String[] args) {
        ResourceBundle rb = ResourceUtil.getResourceBundle( "ha" );
        String path = ResourceUtil.getProperty(rb, "outputPopulation.path");
        HAModel.dm.exportTable("DC LOGSUMS", path+"Logsums");
        System.exit(0);
    }
}
