# @tag{Create CT synthetic firms at the alpha zone level}
# @author{Rick Donnelly} @version{0.9}  @date{12-Oct-2014}
# Generate synthetic firms from alpha zone employment data. This version adds
# total households by alpha zone to the mix.
require(data.table)
require(reshape2)
require(dplyr)
require(stringr)

load("/Users/rick/Models/swim2/ctdev/outputs/t20/ct-runtime-parameters.RData")

create_synthetic_firms <- function() {
    print(str_c("------- create_synthetic_firms -------"), quote=FALSE)
    
	# Read the employment data generated by PECAS for this simulation period and
    # remove the Sectors we will not use further in our analyses
    FN <- paste(RTP[["Working_Folder"]], "Employment.csv", sep='')
    employees <- fread(FN) %>% select(-no_industry, -Total)
    
    # Read the household data generated by SPG for this simulation period, and
    # keep total households.
    FN <- paste(RTP[["Working_Folder"]], "SynPop_Taz_Summary.csv", sep='')
    households <- fread(FN) %>% select(TAZ, as.numeric(TotalHHs)) %>%
        rename(Azone = TAZ, HHOLD_all = TotalHHs)
    keep <- merge(employees, households, by="Azone")
    
    # Start by converting from wide to tall format, so that we have a record for
    # every alpha zone+sector pair
    tall <- melt(keep, id.vars="Azone", variable.name="Sector", value.name="Employees")
    nonzero <- filter(tall, Employees>0)
    print(paste(nrow(tall), "tall records, ", nrow(nonzero), "with non-zero values"),
        quote=FALSE)
    
    # Next we'll append the county the alpha zone falls within, from which we
    # can add FAF region
    FN <- paste(RTP[["CT_Core_Data"]], "alpha2beta.csv", sep='')
    counties <- fread(FN) %>%
        filter(STATEFIPS==41) %>%
        mutate(fips = as.numeric(STATEFIPS)*1000+as.numeric(COUNTYFIPS)) %>%
        select(Azone, fips)
    
    # Assign each to FAF3 region. Clackamas, Columbia, Multnomah, Washington,
    # and Yamhill counties are in the Portland MSA, while the rest are in the
    # Oregon remainder FAF region.
    Portland_MSA <- c(41005, 41009, 41051, 41067, 41071)
    counties$faf_region <- ifelse(counties$fips %in% Portland_MSA, 411, 419)
    
    # Finally, merge county and FAF region to alphas. We'll quietly drop alpha
    # zones outside of Oregon since the key field must exist in both tables.
    alphas <- merge(tall, counties, by="Azone")
    
    # Delete all firms with zero employees (probably not many, but enough to pay
    # attention to) and then assign unique firm ID to the remaining firms
    firms <- filter(alphas, Employees>0)
    firms$firmID <- seq(1, nrow(firms))
    print(paste(max(firms$firmID), "synthetic firms created"), quote=FALSE)
    
    # Write the results and exit stage right
    FN <- str_c(RTP[["Working_Folder"]], "ct-alpha-synthetic-firms.RData")
    save(firms, file=FN)
    if (RTP[["Extended_Trace"]]==TRUE) {
        FN <- str_c(RTP[["Working_Folder"]], "ct-alpha-synthetic-firms.csv")
        write.table(firms, file=FN, sep=',', quote=FALSE, row.names=FALSE)
    }
    
    print("", quote=FALSE)   # Add space before following report
}

SF <- create_synthetic_firms()









