# @tag{Convert annual FAF truckload equivalents to daily flows}
# @author{Rick Donnelly} @email{donnellyr@pbworld.com} @version{1.0} @date{140223}

# Convert from annual to weekly trucks, and within that week, which day they
# will begin or end their journey on. In reality there are many (most?) trips
# that will begin and end on different days because of the distance they travel.
# But if we assume equal probabilities for each day then can assume away that
# difference.
library(dplyr)
library(stringr)
library(data.table)
library(parallel)

sample_FAF_weekly_trucks <- function(random_number_seed) {
    # Be social, and then get to work
    set.seed(random_number_seed)
    print(str_c("------- sample_FAF_weekly_trucks -------"), quote=FALSE)
    print(str_c("Random seed=", random_number_seed), quote=FALSE)
    
    # Start by loading the annual truck trips
    FN <- str_c(RTP[["Working_Folder"]], "faf35-oregon-annual-trucks.RData")
    load(FN)   # Should load a data table called combined
    
    # If we are scaling the external trips then apply the factor to affected
    # trips
    if (RTP[["FAF_external_scaling_factor"]]!=1.0) {
        print(str_c("Scaling factor to correct FAF external equivalencies=",
            RTP[["FAF_external_scaling_factor"]]), quote=FALSE)
        combined$annual_trucks <- ifelse(combined$direction!="Internal",
            round(combined$annual_trucks*RTP[["FAF_external_scaling_factor"]], 0),
            combined$annual_trucks)
    }
    
    # Tell us what our targets are (mostly for debugging and development use)
    weekly_target <- round(sum(combined$annual_trucks)/RTP[["Weeks_Per_Year"]], 0)
    daily_target <- round(weekly_target/7.0, 0)
    print(str_c("Targets: weekly=", weekly_target, " daily=", daily_target),
        quote=FALSE)
    
    # Build a function to sample the week and day for each annual truck trip.
    # Trips occurring on the sampled week and day are returned as fully-
    # attributed daily truck trip data table. This is pretty time-consuming if
    # run monolithically, so using with parallel() or similar is a practical
    # necessity.
    sampleAnnualTruckTrips <- function(x) {
        # Grab row x from the data frame
        replicant <- combined[x,]
        if (RTP[["Extended_Trace"]]==TRUE) {
            print(str_c("sampleAnnualTruckTrips: Processing replicant ", x),
                quote=FALSE)
        }
        trucks_in_replicant <- replicant$annual_trucks
        
        # Grab the probabilities associated with each trip
        draws <- data.table(
            week = sample(1:RTP[["Weeks_Per_Year"]], replicant$annual_trucks,
                replace=TRUE),
            day = sample(1:7, replicant$annual_trucks, replace=TRUE)
        )
        
        # Do any of the trips occur within our target week and day? If so append
        # the important details from the replicant record.
        keep <- filter(draws, week==RTP[["Target_Week"]], day==RTP[["Target_Day"]])
        trucks <- nrow(keep)
        if (trucks>0) {
            keep <- mutate(keep, truckID = seq(1, trucks),
                value = round(replicant$value/trucks_in_replicant, 0),
                tons = round(replicant$tons/trucks_in_replicant, 1),
                fafID = replicant$fafID) %>% select(-week, -day)
            keep <- merge(select(replicant, -zed, -value, -tons, -ton_miles,
                -annual_trucks), keep, by="fafID")
        } else {
            keep <- data.table()   # Delete the contents if no trucks generated
        }
        keep
    }
    
    # Build a database of daily truck trips
    simulation.start <- proc.time()
    numberOfCores <- detectCores()
    print(str_c("Number of cores detected=", numberOfCores), quote=FALSE)
    results <- mclapply(1:nrow(combined), function(x) sampleAnnualTruckTrips(x),
        mc.cores = numberOfCores)
    combined <- rbindlist(results)
    simulation.stop <- proc.time()
    elapsed_seconds <- round((simulation.stop-simulation.start)[["elapsed"]], 1)
    convergence <- round((nrow(combined)/daily_target), 3)
    print(str_c("Simulation time=", elapsed_seconds, " seconds, convergence=",
        convergence), quote=FALSE)
    
    # Give us a brief summary
    if (RTP[["Extended_Trace"]]==TRUE) {
        crosstab <- xtabs(~direction+vehicle_type, data=combined)
        print("Daily truck trips generated by direction and type:", quote=FALSE)
        print(crosstab)
        print("Collapsed by vehicle type:")
        print(rowSums(crosstab))
    }
    
    # Save the output for further processing. By default only write the binary
    # data, but if extended tracing is set in the CT runtime parameters write 
    # the same data in CSV format as well.
    FN <- str_c(RTP[["Working_Folder"]], "faf35-oregon-daily-trucks.RData")
    save(combined, file=FN)
    print(str_c(nrow(combined), " records written to ", FN), quote=FALSE)
    if (RTP[["Extended_Trace"]]==TRUE) {
        FN <- paste(RTP[["Working_Folder"]], "faf35-oregon-daily-trucks.csv")
        write.table(combined, file=FN, quote=FALSE, sep=',', row.names=FALSE)
    }
    
    print("", quote=FALSE)  # Add whitespace before next report
}

DT <- sample_FAF_weekly_trucks(630730)
