# Convert from annual to weekly trucks, and within that week, which day they
# will begin or end their journey on. In reality there are many (most?) trips
# that will begin and end on different days because of the distance they travel.
# But if we assume equal probabilities for each day then can assume away that
# difference.
library(dplyr)
library(stringr)
library(data.table)
library(doParallel)

sample_FAF_weekly_trucks <- function() {
    set.seed(RTP[["ct.random.seed"]])
    print(str_c("------- sample_FAF_weekly_trucks -------"), quote=FALSE)
    
    # Start by loading the annual truck trips
    FN <- str_c(RTP[["Working_Folder"]], "faf35-oregon-annual-trucks.RData")
    load(FN)   # Should load a data table called combined
    
    # If we are scaling the external trips then apply the factor to affected
    # trips
    externalScalingFactor <- as.numeric(RTP[["ct.external.scaling.factor"]])
    if (externalScalingFactor!=1.0) {
        print(str_c("Scaling factor to correct FAF external equivalencies=",
            externalScalingFactor), quote=FALSE)
        combined$annual_trucks <- ifelse(combined$direction!="Internal",
            round(combined$annual_trucks*externalScalingFactor, 0),
            combined$annual_trucks)
    }
    
    # Tell us what our targets are (mostly for debugging and development use)
    weeksPerYear <- as.integer(RTP[["ct.weeks.per.year"]])
    weekly_target <- round(sum(combined$annual_trucks)/weeksPerYear, 0)
    daily_target <- round(weekly_target/7.0, 0)
    print(str_c("Targets: weekly=", weekly_target, " daily=", daily_target),
        quote=FALSE)
    
    # Build a function to sample the week and day for each annual truck trip.
    # Trips occurring on the sampled week and day are returned as fully-
    # attributed daily truck trip data table. This is pretty time-consuming if
    # run monolithically, so using with parallel() or similar is a practical
    # necessity.
    targetWeek <- as.integer(RTP[["ct.target.week"]])
    targetDay <- as.integer(RTP[["ct.target.day"]])
    sampleAnnualTruckTrips <- function(x, RTP) {
        # Grab row x from the data frame
        replicant <- combined[x,]
        # TO-DO: Figure out why "object "RTP" not found" is thrown with it in
        ##if (RTP[["ct.extended.trace"]]=="TRUE") {
        ##    print(str_c("sampleAnnualTruckTrips: Processing replicant ", x),
        ##        quote=FALSE)
        ##}
        trucks_in_replicant <- replicant$annual_trucks
        
        # Grab the probabilities associated with each trip
        draws <- data.table(
            week = sample(1:weeksPerYear, replicant$annual_trucks, replace=TRUE),
            day = sample(1:7, replicant$annual_trucks, replace=TRUE)
        )
        
        # Do any of the trips occur within our target week and day? If so append
        # the important details from the replicant record.
        keep <- filter(draws, week==targetWeek, day==targetDay)
        trucks <- nrow(keep)
        if (trucks>0) {
            keep <- mutate(keep, truckID = seq(1, trucks),
                value = round(replicant$value/trucks_in_replicant, 0),
                tons = round(replicant$tons/trucks_in_replicant, 1),
                fafID = replicant$fafID) %>% select(-week, -day)
            keep <- merge(select(replicant, -zed, -value, -tons, -ton_miles,
                -annual_trucks), keep, by="fafID")
        } else {
            keep <- data.table()   # Delete the contents if no trucks generated
        }
        keep
    }
    
    # Build a database of daily truck trips
    simulation.start <- proc.time()
    numberOfCores <- detectCores()
    print(str_c("Number of cores detected=", numberOfCores), quote=FALSE)
    cluster <- makeCluster(numberOfCores)
    registerDoParallel(cluster)
    combined <- foreach(i=1:nrow(combined), .combine="rbind",
        .packages=c("data.table", "dplyr")) %dopar% sampleAnnualTruckTrips(i, RTP)
    stopCluster(cluster)
    simulation.stop <- proc.time()
    elapsed_seconds <- round((simulation.stop-simulation.start)[["elapsed"]], 1)
    convergence <- round((nrow(combined)/daily_target), 3)
    print(str_c("Simulation time=", elapsed_seconds, " seconds, convergence=",
        convergence), quote=FALSE)
    
    # Give us a brief summary
    if (RTP[["ct.extended.trace"]]=="TRUE") {
        crosstab <- xtabs(~direction+vehicle_type, data=combined)
        print("Daily truck trips generated by direction and type:", quote=FALSE)
        print(crosstab)
        print("Collapsed by vehicle type:")
        print(rowSums(crosstab))
    }
    
    # Save the output for further processing. By default only write the binary
    # data, but if extended tracing is set in the CT runtime parameters write 
    # the same data in CSV format as well.
    FN <- str_c(RTP[["Working_Folder"]], "faf35-oregon-daily-trucks.RData")
    save(combined, file=FN)
    print(str_c(nrow(combined), " records written to ", FN), quote=FALSE)
    if (RTP[["ct.extended.trace"]]=="TRUE") {
        FN <- paste(RTP[["Working_Folder"]], "faf35-oregon-daily-trucks.csv")
        write.table(combined, file=FN, quote=FALSE, sep=',', row.names=FALSE)
    }
    
    print("", quote=FALSE)  # Add whitespace before next report
}

WT <- sample_FAF_weekly_trucks()
