/* Generated by Together */

package com.pb.despair.pi;


//import com.pb.common.util.*;

public class ExponentialPlusBaseFunction extends NumericalDerivativeSingleParameterFunction {
    double base;
    double alpha;
    double lambda;
    double basePrice;

    public ExponentialPlusBaseFunction(double base, double alpha, double lambda, double basePrice) {
        super(0.01);
        this.base = base;
        this.alpha = alpha;
        this.lambda = lambda;
        this.basePrice = basePrice;
    }

    public double evaluate(double price) {
        return base + alpha * Math.exp(lambda * ((price - basePrice) / basePrice));
    }
}

;


