/*
 * Copyright  2005 PB Consult Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/* Generated by Together */

package com.pb.tlumip.ts.old;

import com.pb.models.pecas.TravelUtilityCalculatorInterface;

import java.util.Vector;
public class Trip {
    /**
     * @exception CantGetThereFromHere is the error that is thrown if there is a connectivity error in the network
     */
    public void pickAndLoadAPath() throws CantGetThereFromHere  {
    }

    /**
     * The link that the trip begins from
     */
    private LinkLoad start;

    /**
     * The link that the trip ends at
     */
    private LinkLoad stop;

    /**
     * These are the travel preferences of the Person making the trip.  When the "Trips" are created from the "Tours" (see com.pb.tlumip.pt.Tour) the TravelPreferences need to be copied as well
     */
    private TravelUtilityCalculatorInterface travelPreferences;

    /**
     * associates <{LinkLoad}>
     */
    private Vector thePathIAmUsing;
    public String toString() {return "trip from ("+start+") to ("+stop+")";};
}
