/* Generated by Together */

package com.pb.despair.ts.old;

import java.util.Vector;

/**
 * Global object that keeps track of the assignment periods
 */
public class AllAssignmentPeriods {
    /**
     * Given the start and end time of a trip, this method will return the AssignmentPeriod that the trip should be scheduled in.
     *
     * (problem -- what if a trip spans more than one time period?)
     */
    public static AssignmentPeriod findAssignmentPeriod(float startTime, float endTime) {
     return null;
    }

    /**
     * @associates <{AssignmentPeriod}>
     */
    private Vector assignmentPeriods;

}
