/* Generated by Together */

package com.pb.despair.ts.old;
import java.util.Vector;

/**
 * A network is just a graph of links and associated nodes.
 */
public class Network {
    /**
     * @associates <{LinkInterface}>
     * @link aggregation
     * @supplierCardinality 1..*
     */
    protected Vector links;
}
