/* Generated by Together */

package com.pb.despair.ts.old;

import java.util.Vector;
public class NodeLoad implements NodeInterface {
    /**
     * @associates <{LinkLoad}>
     * @supplierCardinality 0..*
     */
    protected Vector departing;

    /**
     * @supplierCardinality 1
     * @clientCardinality 1..*
     */
    private Node myNode;

    /**
     * @associates <{LinkLoad}>
     * @supplierCardinality 0..*
     */
    protected Vector arri    ;
    public String toString() {return "loaded "+myNode;};
}
