/* Generated by Together */

package com.pb.tlumip.ts.old;

import com.pb.models.pecas.TravelUtilityCalculatorInterface;

import java.util.Vector;
public class Trip {
    /**
     * @exception CantGetThereFromHere is the error that is thrown if there is a connectivity error in the network
     */
    public void pickAndLoadAPath() throws CantGetThereFromHere  {
    }

    /**
     * The link that the trip begins from
     */
    private LinkLoad start;

    /**
     * The link that the trip ends at
     */
    private LinkLoad stop;

    /**
     * These are the travel preferences of the Person making the trip.  When the "Trips" are created from the "Tours" (see com.pb.tlumip.pt.Tour) the TravelPreferences need to be copied as well
     */
    private TravelUtilityCalculatorInterface travelPreferences;

    /**
     * associates <{LinkLoad}>
     */
    private Vector thePathIAmUsing;
    public String toString() {return "trip from ("+start+") to ("+stop+")";};
}
