/* Generated by Together */

package com.pb.despair.ts.old;

import com.pb.models.pecas.TravelAttributesInterface;
public class ZPAttributeArray implements TravelAttributesInterface {
    public ZPAttribute[] theAttributes;

    public ZPAttributeArray(ZPAttribute[] zpars) {
        theAttributes = zpars;
    }

}
